export const browserCoreExamples = [
  "alpha browser status",
  "alpha browser start",
  "alpha browser stop",
  "alpha browser tabs",
  "alpha browser open https://example.com",
  "alpha browser focus abcd1234",
  "alpha browser close abcd1234",
  "alpha browser screenshot",
  "alpha browser screenshot --full-page",
  "alpha browser screenshot --ref 12",
  "alpha browser snapshot",
  "alpha browser snapshot --format aria --limit 200",
  "alpha browser snapshot --efficient",
  "alpha browser snapshot --labels",
];

export const browserActionExamples = [
  "alpha browser navigate https://example.com",
  "alpha browser resize 1280 720",
  "alpha browser click 12 --double",
  'openclaw browser type 23 "hello" --submit',
  "alpha browser press Enter",
  "alpha browser hover 44",
  "alpha browser drag 10 11",
  "alpha browser select 9 OptionA OptionB",
  "alpha browser upload /tmp/openclaw/uploads/file.pdf",
  'openclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "alpha browser dialog --accept",
  'openclaw browser wait --text "Done"',
  "alpha browser evaluate --fn '(el) => el.textContent' --ref 7",
  "alpha browser console --level error",
  "alpha browser pdf",
];
