export const browserCoreExamples = [
  "nicholsbot browser status",
  "nicholsbot browser start",
  "nicholsbot browser stop",
  "nicholsbot browser tabs",
  "nicholsbot browser open https://example.com",
  "nicholsbot browser focus abcd1234",
  "nicholsbot browser close abcd1234",
  "nicholsbot browser screenshot",
  "nicholsbot browser screenshot --full-page",
  "nicholsbot browser screenshot --ref 12",
  "nicholsbot browser snapshot",
  "nicholsbot browser snapshot --format aria --limit 200",
  "nicholsbot browser snapshot --efficient",
  "nicholsbot browser snapshot --labels",
];

export const browserActionExamples = [
  "nicholsbot browser navigate https://example.com",
  "nicholsbot browser resize 1280 720",
  "nicholsbot browser click 12 --double",
  'openclaw browser type 23 "hello" --submit',
  "nicholsbot browser press Enter",
  "nicholsbot browser hover 44",
  "nicholsbot browser drag 10 11",
  "nicholsbot browser select 9 OptionA OptionB",
  "nicholsbot browser upload /tmp/file.pdf",
  'openclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "nicholsbot browser dialog --accept",
  'openclaw browser wait --text "Done"',
  "nicholsbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "nicholsbot browser console --level error",
  "nicholsbot browser pdf",
];
